#!/bin/bash
APP_NAME="gol"
EXECUTABLE="run.sh"
TEST_DIRECTORY="tests/Experiments/golExperimentsNativeEUROPAR/"
NUMBER_ITERATIONS=100
NUMBER_INNER_ITERATIONS=10
NUMBER_CLUSTERS=16
NUMBER_PE=16
EXECUTION_TIMES=5
HTILE_SIZE=$1
WTILE_SIZE=$2

for INPUT_SIZE in 12288
do
  #for TILE_SIZE in 256
  #do
    mkdir -p tests/Experiments/golExperimentsNativeEUROPAR/spec${INPUT_SIZE}${HTILE_SIZE}${WTILE_SIZE}/
    for i in `seq 1 ${EXECUTION_TIMES}`
    do
      echo "Running test..."
      echo "${INPUT_SIZE}_${HTILE_SIZE}_${WTILE_SIZE}_${NUMBER_CLUSTERS}_${NUMBER_PE}_${NUMBER_ITERATIONS}_${i}"
      ./${EXECUTABLE} ${INPUT_SIZE} ${INPUT_SIZE} ${HTILE_SIZE} ${WTILE_SIZE} ${NUMBER_ITERATIONS} ${NUMBER_INNER_ITERATIONS} ${NUMBER_CLUSTERS} ${NUMBER_PE} | tee -a ${TEST_DIRECTORY}spec${INPUT_SIZE}${HTILE_SIZE}${WTILE_SIZE}/${APP_NAME}_test_${INPUT_SIZE}_${HTILE_SIZE}_${WTILE_SIZE}_${NUMBER_CLUSTERS}_${NUMBER_PE}_${NUMBER_ITERATIONS}_${i}.txt
      sleep 1
    done
  #done
done
